name: Push to docker hub

on:
  push:
    tags: ["v*.*.*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "ğŸŒ´ Set output"
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: "ğŸ”¨ Set up Go"
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: "ğŸ“¦ Build web-analyser artifacts"
        run: make build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: "â›´ Set up docker"
        uses: docker/setup-buildx-action@v2

      - name: "ğŸ™‹â€â™‚ï¸ â›´ Login to DockerHub"
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "âš™ï¸ Build and ğŸ“ push"
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: kanishka/web-scraper:latest, kanishka/web-scraper:${{ steps.vars.outputs.tag }}
